# CS2 Lampe Réactive - Blueprint pour Home Assistant
# Version: 2.1.0
# Date: 2025-01-28
# Description: Contrôle intelligent de lampes RGB basé sur les événements CS2
#              avec sauvegarde/restauration automatique de l'état

blueprint:
  name: CS2 Lampe Réactive
  description: Contrôle des lampes RGB en fonction des événements du jeu CS2 via CS2MQTT avec sauvegarde/restauration automatique
  domain: automation
  input:
    # ===== CONFIGURATION GÉNÉRALE =====
    general_section:
      collapsed: true
      name: "General"
      icon: mdi:cog
      input:
        light_entities:
          name: 💡 Lampes à contrôler
          description: Les lampes RGB qui réagiront aux événements CS2 (une ou plusieurs)
          selector:
            entity:
              domain: light
              multiple: true
        
        connection_sensor:
          name: 🔌 Sensor de connexion
          description: Sensor binaire indiquant l'état de connexion au jeu (on=Connecté, off=Déconnecté)
          selector:
            entity:
              domain: binary_sensor
    
    # ===== CONFIGURATION ÉQUIPES =====
    team_section:
      collapsed: true
      name: "Team"
      icon: mdi:account-group
      input:
        enable_team_color:
          name: "Activer les couleurs d'équipe"
          description: Active l'affichage de la couleur d'équipe pendant la manche
          default: true
          selector:
            boolean:
        
        current_team:
          name: "Sensor équipe actuelle"
          description: Sensor indiquant l'équipe actuelle (T ou CT)
          selector:
            entity:
              domain: sensor
        
        round_phase:
          name: "Sensor phase de round"
          description: Sensor indiquant la phase du round (Over/Live/Freezetime)
          selector:
            entity:
              domain: sensor
        
        color_t:
          name: "Couleur équipe T"
          description: Couleur pour l'équipe Terrorist
          default: [255, 180, 0]
          selector:
            color_rgb:
        
        brightness_t:
          name: "Luminosité équipe T (%)"
          description: Luminosité pour l'équipe Terrorist
          default: 25
          selector:
            number:
              min: 1
              max: 100
              unit_of_measurement: "%"
        
        color_ct:
          name: "Couleur équipe CT"
          description: Couleur pour l'équipe Counter-Terrorist
          default: [0, 100, 255]
          selector:
            color_rgb:
        
        brightness_ct:
          name: "Luminosité équipe CT (%)"
          description: Luminosité pour l'équipe Counter-Terrorist
          default: 25
          selector:
            number:
              min: 1
              max: 100
              unit_of_measurement: "%"
    
    # ===== FLASH =====
    flash_section:
      collapsed: true
      name: "Flash"
      icon: mdi:flash
      input:
        enable_flash:
          name: "Activer l'effet Flash"
          description: Active l'effet blanc quand le joueur est flashé
          default: true
          selector:
            boolean:
        
        flashed_sensor:
          name: "Sensor Flash"
          description: Sensor indiquant si le joueur est flashé (valeurs "True" ou "False" en texte)
          selector:
            entity:
              domain: sensor
        
        flash_color:
          name: "Couleur du flash"
          description: Couleur de l'effet flash
          default: [255, 255, 255]
          selector:
            color_rgb:
        
        flash_brightness:
          name: "Luminosité du flash (%)"
          description: Luminosité de l'effet flash
          default: 100
          selector:
            number:
              min: 1
              max: 100
              unit_of_measurement: "%"
    
    # ===== SMOKE =====
    smoke_section:
      collapsed: true
      name: "Smoke"
      icon: mdi:weather-fog
      input:
        enable_smoke:
          name: "Activer l'effet Smoke"
          description: Active l'effet blanc qui s'assombrit avec la fumée
          default: true
          selector:
            boolean:
        
        smoked_sensor:
          name: "Sensor Smoke"
          description: Sensor indiquant le niveau de smoke (0-100%)
          selector:
            entity:
              domain: sensor
        
        smoke_color:
          name: "Couleur de base de la fumée"
          description: Couleur de base (blanc par défaut, s'assombrit progressivement avec le niveau de smoke)
          default: [255, 255, 255]
          selector:
            color_rgb:
    
    # ===== BURNING =====
    flame_section:
      collapsed: true
      name: "Flame"
      icon: mdi:fire-alert
      input:
        enable_burning:
          name: "Activer l'effet Burning"
          description: Active l'effet de flamme quand le joueur brûle
          default: true
          selector:
            boolean:
        
        burning_sensor:
          name: "Sensor Burning"
          description: Sensor indiquant si le joueur brûle (0-100%)
          selector:
            entity:
              domain: sensor
        
        flame_color_high:
          name: "Couleur flamme intense"
          description: Couleur de la flamme intense
          default: [255, 50, 0]
          selector:
            color_rgb:
        
        flame_color_medium:
          name: "Couleur flamme moyenne"
          description: Couleur de la flamme moyenne
          default: [255, 100, 0]
          selector:
            color_rgb:
        
        flame_color_low:
          name: "Couleur flamme basse"
          description: Couleur de la flamme basse
          default: [255, 150, 0]
          selector:
            color_rgb:
    
    # ===== BOMBE =====
    bomb_section:
      collapsed: true
      name: "Bomb"
      icon: mdi:bomb
      input:
        enable_bomb:
          name: "Activer les effets Bombe"
          description: Active les effets de bombe (clignotement rouge/bleu fixe)
          default: true
          selector:
            boolean:
        
        bomb_sensor:
          name: "Sensor Bombe"
          description: Sensor indiquant l'état de la bombe (Inactive/Planted/Exploded/Defused)
          selector:
            entity:
              domain: sensor
        
        bomb_planted_color:
          name: "Couleur bombe plantée"
          description: Couleur du clignotement quand la bombe est plantée
          default: [255, 0, 0]
          selector:
            color_rgb:
        
        bomb_planted_brightness:
          name: "Luminosité bombe plantée (%)"
          description: Luminosité du clignotement quand la bombe est plantée
          default: 100
          selector:
            number:
              min: 1
              max: 100
              unit_of_measurement: "%"
        
        bomb_defused_color:
          name: "Couleur bombe diffusée"
          description: Couleur quand la bombe est diffusée
          default: [0, 150, 255]
          selector:
            color_rgb:
        
        bomb_defused_brightness:
          name: "Luminosité bombe diffusée (%)"
          description: Luminosité quand la bombe est diffusée
          default: 100
          selector:
            number:
              min: 1
              max: 100
              unit_of_measurement: "%"

mode: restart
max_exceeded: silent

variables:
  lights: !input general_section.light_entities
  connection: !input general_section.connection_sensor
  team: !input team_section.current_team
  flashed: !input flash_section.flashed_sensor
  smoked: !input smoke_section.smoked_sensor
  burning: !input flame_section.burning_sensor
  bomb: !input bomb_section.bomb_sensor
  round_phase_sensor: !input team_section.round_phase
  # Couleurs et luminosités équipes
  t_color: !input team_section.color_t
  t_brightness: !input team_section.brightness_t
  ct_color: !input team_section.color_ct
  ct_brightness: !input team_section.brightness_ct
  # Flash
  flash_col: !input flash_section.flash_color
  flash_bright: !input flash_section.flash_brightness
  # Smoke
  smoke_col: !input smoke_section.smoke_color
  # Burning
  flame_high: !input flame_section.flame_color_high
  flame_med: !input flame_section.flame_color_medium
  flame_low: !input flame_section.flame_color_low
  # Bombe
  bomb_plant_col: !input bomb_section.bomb_planted_color
  bomb_plant_bright: !input bomb_section.bomb_planted_brightness
  bomb_defuse_col: !input bomb_section.bomb_defused_color
  bomb_defuse_bright: !input bomb_section.bomb_defused_brightness
  # Options d'activation
  enable_team: !input team_section.enable_team_color
  enable_flash_effect: !input flash_section.enable_flash
  enable_smoke_effect: !input smoke_section.enable_smoke
  enable_burning_effect: !input flame_section.enable_burning
  enable_bomb_effect: !input bomb_section.enable_bomb

trigger:
  # Trigger de connexion/déconnexion
  - platform: state
    entity_id: !input general_section.connection_sensor
  # Triggers des événements de jeu
  - platform: state
    entity_id: !input team_section.current_team
  - platform: state
    entity_id: !input flash_section.flashed_sensor
  - platform: state
    entity_id: !input smoke_section.smoked_sensor
  - platform: state
    entity_id: !input flame_section.burning_sensor
  - platform: state
    entity_id: !input bomb_section.bomb_sensor
  - platform: state
    entity_id: !input team_section.round_phase

action:
  - choose:
      # ===== SAUVEGARDE DE L'ÉTAT (Connexion au jeu) =====
      - conditions:
          - condition: state
            entity_id: !input general_section.connection_sensor
            state: "on"
        sequence:
          # Sauvegarder l'état de chaque lampe dans une scene
          - service: scene.create
            data:
              scene_id: cs2_lights_backup
              snapshot_entities: !input general_section.light_entities
      
      # ===== RESTAURATION DE L'ÉTAT (Déconnexion du jeu) =====
      - conditions:
          - condition: state
            entity_id: !input general_section.connection_sensor
            state: "off"
        sequence:
          # Restaurer l'état des lampes
          - service: scene.turn_on
            target:
              entity_id: scene.cs2_lights_backup
            data:
              transition: 2
      
      # ===== EFFETS DE JEU (seulement si connecté) =====
      # PRIORITÉ 1 : Flash (blanc)
      - conditions:
          - condition: state
            entity_id: !input general_section.connection_sensor
            state: "on"
          - condition: template
            value_template: "{{ enable_flash_effect }}"
          - condition: template
            value_template: >
              {% set flash_state = states(flashed) | string | lower %}
              {{ flash_state == 'true' }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input general_section.light_entities
            data:
              brightness_pct: "{{ flash_bright }}"
              rgb_color: "{{ flash_col }}"
              transition: 0
      
      # PRIORITÉ 2 : Bombe plantée (clignotement rouge)
      - conditions:
          - condition: state
            entity_id: !input general_section.connection_sensor
            state: "on"
          - condition: template
            value_template: "{{ enable_bomb_effect }}"
          - condition: state
            entity_id: !input bomb_section.bomb_sensor
            state: "Planted"
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: !input bomb_section.bomb_sensor
                  state: "Planted"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input general_section.light_entities
                  data:
                    brightness_pct: "{{ bomb_plant_bright }}"
                    rgb_color: "{{ bomb_plant_col }}"
                    transition: 0
                - delay:
                    milliseconds: 500
                - service: light.turn_off
                  target:
                    entity_id: !input general_section.light_entities
                  data:
                    transition: 0
                - delay:
                    milliseconds: 500
      
      # PRIORITÉ 3 : Bombe diffusée (bleu fixe)
      - conditions:
          - condition: state
            entity_id: !input general_section.connection_sensor
            state: "on"
          - condition: template
            value_template: "{{ enable_bomb_effect }}"
          - condition: state
            entity_id: !input bomb_section.bomb_sensor
            state: "Defused"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input general_section.light_entities
            data:
              brightness_pct: "{{ bomb_defuse_bright }}"
              rgb_color: "{{ bomb_defuse_col }}"
              transition: 1
      
      # PRIORITÉ 4 : Burning (effet flamme)
      - conditions:
          - condition: state
            entity_id: !input general_section.connection_sensor
            state: "on"
          - condition: template
            value_template: "{{ enable_burning_effect }}"
          - condition: template
            value_template: >
              {{ states(burning) | int(0) > 0 }}
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {{ states(burning) | int(0) > 0 }}
              sequence:
                # Flamme intense
                - service: light.turn_on
                  target:
                    entity_id: !input general_section.light_entities
                  data:
                    brightness_pct: >
                      {{ states(burning) | int(0) }}
                    rgb_color: "{{ flame_high }}"
                    transition: 0
                - delay:
                    milliseconds: 100
                # Flamme moyenne
                - service: light.turn_on
                  target:
                    entity_id: !input general_section.light_entities
                  data:
                    brightness_pct: >
                      {{ (states(burning) | int(0) * 0.7) | int }}
                    rgb_color: "{{ flame_med }}"
                    transition: 0
                - delay:
                    milliseconds: 100
                # Flamme basse
                - service: light.turn_on
                  target:
                    entity_id: !input general_section.light_entities
                  data:
                    brightness_pct: >
                      {{ (states(burning) | int(0) * 0.5) | int }}
                    rgb_color: "{{ flame_low }}"
                    transition: 0
                - delay:
                    milliseconds: 100
      
      # PRIORITÉ 5 : Smoke (blanc progressif qui s'assombrit)
      - conditions:
          - condition: state
            entity_id: !input general_section.connection_sensor
            state: "on"
          - condition: template
            value_template: "{{ enable_smoke_effect }}"
          - condition: template
            value_template: >
              {{ states(smoked) | int(0) > 0 }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input general_section.light_entities
            data:
              brightness_pct: >
                {% set smoke_level = states(smoked) | int(0) %}
                {% set min_brightness = 10 %}
                {% set max_brightness = 100 %}
                {{ max_brightness - ((max_brightness - min_brightness) * smoke_level / 100) | int }}
              rgb_color: "{{ smoke_col }}"
              transition: 0.5
      
      # PRIORITÉ 6 : Couleur d'équipe par défaut
      - conditions:
          - condition: state
            entity_id: !input general_section.connection_sensor
            state: "on"
          - condition: template
            value_template: "{{ enable_team }}"
          - condition: template
            value_template: >
              {{ states(round_phase_sensor) in ['Live', 'Freezetime'] }}
        sequence:
          - choose:
              # Équipe T
              - conditions:
                  - condition: state
                    entity_id: !input team_section.current_team
                    state: "T"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input general_section.light_entities
                    data:
                      brightness_pct: "{{ t_brightness }}"
                      rgb_color: "{{ t_color }}"
                      transition: 1
              
              # Équipe CT
              - conditions:
                  - condition: state
                    entity_id: !input team_section.current_team
                    state: "CT"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input general_section.light_entities
                    data:
                      brightness_pct: "{{ ct_brightness }}"
                      rgb_color: "{{ ct_color }}"
                      transition: 1
