#V2
blueprint:
  name: CS2 Lampe Réactive
  description: Contrôle une lampe RGB en fonction des événements du jeu CS2 via CS2MQTT
  domain: automation
  input:
    light_entity:
      name: 💡 Lampe à contrôler
      description: La lampe RGB qui réagira aux événements CS2
      selector:
        entity:
          domain: light
    
    # ===== CONFIGURATION ÉQUIPES =====
    enable_team_color:
      name: "⚔️ ÉQUIPES - Activer les couleurs d'équipe"
      description: Active l'affichage de la couleur d'équipe pendant la manche
      default: true
      selector:
        boolean:
    
    current_team:
      name: "⚔️ ÉQUIPES - Sensor équipe actuelle"
      description: Sensor indiquant l'équipe actuelle (T ou CT)
      selector:
        entity:
          domain: sensor
    
    round_phase:
      name: "⚔️ ÉQUIPES - Sensor phase de round"
      description: Sensor indiquant la phase du round (Over/Live/Freezetime)
      selector:
        entity:
          domain: sensor
    
    color_t:
      name: "⚔️ ÉQUIPES - Couleur équipe T"
      description: Couleur pour l'équipe Terrorist
      default: [255, 180, 0]
      selector:
        color_rgb:
    
    color_ct:
      name: "⚔️ ÉQUIPES - Couleur équipe CT"
      description: Couleur pour l'équipe Counter-Terrorist
      default: [0, 100, 255]
      selector:
        color_rgb:
    
    # ===== FLASH =====
    enable_flash:
      name: "⚡ FLASH - Activer l'effet Flash"
      description: Active l'effet blanc quand le joueur est flashé
      default: true
      selector:
        boolean:
    
    flashed_sensor:
      name: "⚡ FLASH - Sensor Flash"
      description: Sensor indiquant si le joueur est flashé (valeurs "True" ou "False" en texte)
      selector:
        entity:
          domain: sensor
    
    # ===== SMOKE =====
    enable_smoke:
      name: "💨 SMOKE - Activer l'effet Smoke"
      description: Active l'effet gris quand le joueur est dans la fumée
      default: true
      selector:
        boolean:
    
    smoked_sensor:
      name: "💨 SMOKE - Sensor Smoke"
      description: Sensor indiquant le niveau de smoke (0-100%)
      selector:
        entity:
          domain: sensor
    
    # ===== BURNING =====
    enable_burning:
      name: "🔥 BURNING - Activer l'effet Burning"
      description: Active l'effet de flamme quand le joueur brûle
      default: true
      selector:
        boolean:
    
    burning_sensor:
      name: "🔥 BURNING - Sensor Burning"
      description: Sensor indiquant si le joueur brûle (0-100%)
      selector:
        entity:
          domain: sensor
    
    # ===== BOMBE =====
    enable_bomb:
      name: "💣 BOMBE - Activer les effets Bombe"
      description: Active les effets de bombe (clignotement rouge/bleu fixe)
      default: true
      selector:
        boolean:
    
    bomb_sensor:
      name: "💣 BOMBE - Sensor Bombe"
      description: Sensor indiquant l'état de la bombe (inactive/planted/exploded/defused)
      selector:
        entity:
          domain: sensor

mode: restart
max_exceeded: silent

variables:
  light: !input light_entity
  team: !input current_team
  flashed: !input flashed_sensor
  smoked: !input smoked_sensor
  burning: !input burning_sensor
  bomb: !input bomb_sensor
  round_phase_sensor: !input round_phase
  t_color: !input color_t
  ct_color: !input color_ct
  enable_team: !input enable_team_color
  enable_flash_effect: !input enable_flash
  enable_smoke_effect: !input enable_smoke
  enable_burning_effect: !input enable_burning
  enable_bomb_effect: !input enable_bomb

trigger:
  - platform: state
    entity_id: !input current_team
  - platform: state
    entity_id: !input flashed_sensor
  - platform: state
    entity_id: !input smoked_sensor
  - platform: state
    entity_id: !input burning_sensor
  - platform: state
    entity_id: !input bomb_sensor
  - platform: state
    entity_id: !input round_phase

action:
  - choose:
      # PRIORITÉ 1 : Flash (blanc)
      - conditions:
          - condition: template
            value_template: "{{ enable_flash_effect }}"
          - condition: template
            value_template: >
              {% set flash_state = states(flashed) | string | lower %}
              {{ flash_state == 'true' }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              brightness_pct: 100
              rgb_color: [255, 255, 255]
              transition: 0
      
      # PRIORITÉ 2 : Bombe plantée (clignotement rouge selon timer)
      - conditions:
          - condition: template
            value_template: "{{ enable_bomb_effect }}"
          - condition: state
            entity_id: !input bomb_sensor
            state: "planted"
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: !input bomb_sensor
                  state: "planted"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light_entity
                  data:
                    brightness_pct: 100
                    rgb_color: [255, 0, 0]
                    transition: 0
                - delay:
                    milliseconds: 500
                - service: light.turn_off
                  target:
                    entity_id: !input light_entity
                  data:
                    transition: 0
                - delay:
                    milliseconds: 500
      
      # PRIORITÉ 3 : Bombe diffusée (bleu fixe)
      - conditions:
          - condition: template
            value_template: "{{ enable_bomb_effect }}"
          - condition: state
            entity_id: !input bomb_sensor
            state: "defused"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              brightness_pct: 100
              rgb_color: [0, 150, 255]
              transition: 1
      
      # PRIORITÉ 4 : Burning (effet flamme)
      - conditions:
          - condition: template
            value_template: "{{ enable_burning_effect }}"
          - condition: template
            value_template: >
              {{ states(burning) | int(0) > 0 }}
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {{ states(burning) | int(0) > 0 }}
              sequence:
                # Flamme intense
                - service: light.turn_on
                  target:
                    entity_id: !input light_entity
                  data:
                    brightness_pct: >
                      {{ states(burning) | int(0) }}
                    rgb_color: [255, 50, 0]
                    transition: 0
                - delay:
                    milliseconds: 100
                # Flamme moyenne
                - service: light.turn_on
                  target:
                    entity_id: !input light_entity
                  data:
                    brightness_pct: >
                      {{ (states(burning) | int(0) * 0.7) | int }}
                    rgb_color: [255, 100, 0]
                    transition: 0
                - delay:
                    milliseconds: 100
                # Flamme basse
                - service: light.turn_on
                  target:
                    entity_id: !input light_entity
                  data:
                    brightness_pct: >
                      {{ (states(burning) | int(0) * 0.5) | int }}
                    rgb_color: [255, 150, 0]
                    transition: 0
                - delay:
                    milliseconds: 100
      
      # PRIORITÉ 5 : Smoke (gris)
      - conditions:
          - condition: template
            value_template: "{{ enable_smoke_effect }}"
          - condition: template
            value_template: >
              {{ states(smoked) | int(0) > 0 }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              brightness_pct: >
                {{ states(smoked) | int(0) }}
              rgb_color: [128, 128, 128]
              transition: 0.5
      
      # PRIORITÉ 6 : Couleur d'équipe par défaut
      - conditions:
          - condition: template
            value_template: "{{ enable_team }}"
          - condition: template
            value_template: >
              {{ states(round_phase_sensor) in ['Live', 'Freezetime'] }}
        sequence:
          - choose:
              # Équipe T
              - conditions:
                  - condition: state
                    entity_id: !input current_team
                    state: "T"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data:
                      brightness_pct: 25
                      rgb_color: !input color_t
                      transition: 1
              
              # Équipe CT
              - conditions:
                  - condition: state
                    entity_id: !input current_team
                    state: "CT"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data:
                      brightness_pct: 25
                      rgb_color: !input color_ct
                      transition: 1
    
    # Par défaut : éteindre la lampe si round terminé
    default:
      - service: light.turn_off
        target:
          entity_id: !input light_entity
        data:
          transition: 2
