blueprint:
  name: CS2 Reactive Lights
  description: "Contrôle les lumières en fonction de l'état d'une partie de CS2 via Game State Integration."
  domain: automation
  input:
    light_target:
      name: Lumières
      description: Les lumières à contrôler.
      selector:
        target:
          entity:
            domain: light

    team_section:
      name: Couleurs d'Équipes
      icon: mdi:account-group
      input:
        enable_team_color:
          name: Activer les couleurs d'équipe
          default: true
          selector:
            boolean: {}
        current_team:
          name: Capteur d'équipe actuelle
          selector:
            entity:
              domain: sensor
        round_phase:
          name: Capteur de phase du round
          selector:
            entity:
              domain: sensor
        color_ct:
          name: Couleur CT
          default: [0, 150, 255]
          selector:
            color_rgb: {}
        color_t:
          name: Couleur Terroriste
          default: [255, 100, 0]
          selector:
            color_rgb: {}

    bomb_section:
      name: Bombe
      icon: mdi:bomb
      input:
        enable_bomb:
          name: Activer l'effet bombe
          default: true
          selector:
            boolean: {}
        bomb_sensor:
          name: Capteur d'état de la bombe
          selector:
            entity:
              domain: sensor

    flash_section:
      name: Aveuglement (Flash)
      icon: mdi:eye-off
      input:
        enable_flash:
          name: Activer l'effet flash
          default: true
          selector:
            boolean: {}
        flashed_sensor:
          name: Capteur d'aveuglement (alpha)
          selector:
            entity:
              domain: sensor

    smoke_section:
      name: Fumée (Smoke)
      icon: mdi:cloud
      input:
        enable_smoke:
          name: Activer l'effet fumée
          default: true
          selector:
            boolean: {}
        smoked_sensor:
          name: Capteur de fumée (alpha)
          selector:
            entity:
              domain: sensor

    burning_section:
      name: Feu (Molotov/Incendiaire)
      icon: mdi:fire
      input:
        enable_burning:
          name: Activer l'effet feu
          default: true
          selector:
            boolean: {}
        burning_sensor:
          name: Capteur de brûlure (alpha)
          selector:
            entity:
              domain: sensor

mode: restart

trigger:
  - platform: state
    entity_id: !input current_team
  - platform: state
    entity_id: !input round_phase
  - platform: state
    entity_id: !input bomb_sensor
  - platform: state
    entity_id: !input flashed_sensor
  - platform: state
    entity_id: !input smoked_sensor
  - platform: state
    entity_id: !input burning_sensor

action:
  - choose:
      # Effet Flash
      - conditions:
          - condition: template
            value_template: "{{ states(flashed_sensor) | float(0) > 100 and (enable_flash == true) }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_pct: 100
              rgb_color: [255, 255, 255]

      # Effet Fumée
      - conditions:
          - condition: template
            value_template: "{{ states(smoked_sensor) | float(0) > 100 and (enable_smoke == true) }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_pct: 30
              rgb_color: [200, 200, 200]

      # Effet Feu
      - conditions:
          - condition: template
            value_template: "{{ states(burning_sensor) | float(0) > 100 and (enable_burning == true) }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_pct: 100
              rgb_color: [255, 50, 0]

      # Couleur d'équipe par défaut
      - conditions:
          - condition: template
            value_template: "{{ enable_team_color == true }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              rgb_color: >
                {% if states(current_team) == 'CT' %}
                  {{ color_ct }}
                {% else %}
                  {{ color_t }}
                {% endif %}
              brightness_pct: 100

    default: []

variables:
  # On mappe les inputs dans des variables pour les utiliser dans les templates
  enable_team_color: !input enable_team_color
  current_team: !input current_team
  color_ct: !input color_ct
  color_t: !input color_t
  enable_flash: !input enable_flash
  flashed_sensor: !input flashed_sensor
  enable_smoke: !input enable_smoke
  smoked_sensor: !input smoked_sensor
  enable_burning: !input enable_burning
  burning_sensor: !input burning_sensor
